template = "https://github.com/giellalt/template-lang-und"
rev_id = 273
template_sha = "9f0fbd0d561cacc624db71c646d1ccc4d51920f6"

[replacements]
__GLOTTOLOG_ID__ = "puru1264"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-pur"
__UND2C__ = "pur"
__UNDEFINED__ = "Purubora"
__UND__ = "pur"
