template = "https://github.com/giellalt/template-lang-und"
rev_id = 264
template_sha = "120f384c016282eb1fbbcc762e0ac6064a37eb45"

[replacements]
__GLOTTOLOG_ID__ = "puru1264"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-pur"
__UND2C__ = "pur"
__UNDEFINED__ = "Purubora"
__UND__ = "pur"
