template = "https://github.com/giellalt/template-lang-und"
rev_id = 228
template_sha = "654d6d96d3db7084b1105ed558300bf271d2b0d2"

[replacements]
__LICENSE__ = "GPLv3"
__REPO__ = "lang-pur"
__UND2C__ = "pur"
__UNDEFINED__ = "Purubora"
__UND__ = "pur"
